### ISSUE TITLE
Fail to parse URI

### ISSUE THREAD

**Issue by JJ** [croservices/cro-http#115]
I'm getting this error, apparently in Cro::URI:
```
    Unable to parse URI 'sendMessage?chat_id=-298837738&text=%60##########%0A##########%0A##########%0A##########%0A##########%0A##########%0A######@###%0A%60%20para%20@JJMerelo': unexpected text at end
      in method panic at /home/jmerelo/.rakudobrew/moar-2020.08.2/install/share/perl6/site/sources/15F8C054F18B426F66A859D43B4D948BF207C69D (Cro::Uri) line 202
```

Any idea what's going on? Besides the evident newlines in the middle of the string.

**Comment by jnthn** [comment]
The newlines are encoded, though, so probably not the issue. The `#` is not encoded, but I'd think it should be in the query string, otherwise it's ambiguous with the fragment specifier.

**Comment by JJ** [comment]
It's gone through uri_encode. So really no idea... It's maybe a Cro::Core issue, since Cro::URI is there?
Should I maybe use Cro::Uri to encode instead?

**Comment by JJ** [comment]
Maybe it's the minus sign after chat_id=?

**Comment by JJ** [comment]
NO, not the minus. It also fails with :

    sendMessage?chat_id=14974002&text=%60##########%0A##########%0A##@#######%0A##########%0A##########%0A##########%0A##########%0A%60%20para%20@JJMerelo

**Comment by jnthn** [comment]
The problem seems to be that `encode_uri` is being tasked with doing the impossible. It's given a complete URI and told to encode it. It then assumes that if a character is meaningful in a URI it should leave it alone. But in this case, the `#` is data, not semantic. There's no way it can really know that.

How are you assembling the URI? Can you use [the query option](https://cro.services/docs/reference/cro-http-client#Adding_query_string_parameters) instead, and then `Cro::HTTP::Client` should see to having things encoded correctly?

**Comment by JJ** [comment]
I'm using telegram-bot. But I don't really need the hashes. I can use anything else. Thanks a lot!
