### ISSUE TITLE
Multipart body should `does Associative` and be hashy

### ISSUE THREAD

**Issue by jnthn** [croservices/cro-http#12]
Our [current Multipart class](https://github.com/croservices/cro-http/blob/193cbdd9ff70abe2777280466eeaf0f7b3935144/lib/Cro/HTTP/Body.pm6#L59) does not yet do the `Associative` role and implement `AT-KEY` and `EXISTS-KEY`.

We should do something like we do for `WWWFormUrlEncoded` (earlier in that file) - that is, build up an internal hash keyed on name on the first call to `AT-KEY` or `EXISTS-KEY`. It should return the `Part` with that name, or a `Cro::HTTP::MultiValue` containing the `Part` objects.

Finally, so you can mostly pretend a `WWWFormUrlEncoded` and a `Multipart` are about the same, then I suggest we add a `Stringy` and `Str` methods to `Part` that delegate to `body-text`.

We should have tests for these also.

**Comment by Altai-man** [comment]
https://github.com/croservices/cro-http/commit/cdb21c42ceebe401ebd24c3a9fdbfa23fbed58e4 should close it.
I have made tests a bit "high-levelish", we don't have a separate `http-body.t` for this things, so router(since destructuring is kind of router feature) seem like an appropriate places.

Everything destructures and `Str` transformation works too this way.

**Comment by Altai-man** [comment]
Closing as old enough...
