### ISSUE TITLE
Feature request: debug tracing

### ISSUE THREAD

**Issue by Altreus** [croservices/cro-http#40]
This would be a general Cro feature I think. Sometimes I just want to enable a trace mode so that I can see what Cro is doing. My current use case is that I would like to run a curl with the same headers, URI, etc that Cro is sending, so I can tweak them until the other server stops complaining.

I am sure there would be a discussion on how best to do this, and I wasn't sure how best to fit it in, so I haven't got a patch or anything that makes a start on this.

**Comment by jnthn** [comment]
It already exists.

* If using the `cro` development tool to run services, use `cro trace` instead of `cro run` ([documentation](https://cro.services/docs/cro-tool#Tracing_Services))
* If running manually or it's a client, set `CRO_TRACE=1` in the environment

Sounds like you're doing the second, and probably we should better document this. Would [a mention of it here](https://cro.services/docs/reference/cro-http-client) have been helpful? If not, where did you look, so we can get it in the right place? :-)

**Comment by Altreus** [comment]
Thanks @jnthn - I definitely looked at the page you linked so that would be a great place to add a couple of paragraphs on debugging.

**Comment by jnthn** [comment]
Documentation added in https://github.com/croservices/cro/commit/aa40f51d2f.
