### ISSUE TITLE
the header value is being lower-cased with http/2 (should be just the key)

### ISSUE THREAD

**Issue by donpdonp** [croservices/cro-http#44]
I'm hand-rolling the http-signature spec and its been working until it connected to an http/2 server. The value of the header field has been lowercased, when the spec says the key should be lowercased. Repeating the same request with :http<1.1> fixes the problem.

**Comment by nightpool** [comment]
The main problem here is that HTTP header *values* are case-sensitive. Lower-casing them breaks stuff like Base64 encoded keys, bearer token values, and all sorts of other collateral damage.

**Comment by donpdonp** [comment]
im saying the cro http client library is converting the header value to lowercase when it should only be converting the header key.

**Comment by nightpool** [comment]
I agree. I just wanted to make it a little more clear what the consequences were :D

**Comment by Altai-man** [comment]
Thanks for your notice. This issue was already noticed and addressed last weekend, the fix commit is https://github.com/croservices/cro-http/commit/049e0cdb357c8d039685e354424c33eeeb8179e2.
Next cro release is likely to happen soon(though I cannot say exact date right now). If in a hurry, it is recommended to either use HTTP/1.1 or use latest module version from git.
