### ISSUE TITLE
CRO_HTTP_CLIENT_TRACE - env variable?

### ISSUE THREAD

**Issue by nige123** [croservices/cro-http#9]
Really like the design of Cro with its signature powered route dispatching etc.

This isn't really a bug - more a newbie would-like-to-have. I'm writing a RESTful API client - based on Cro::HTTP::Client. The service is returning 403 responses - probably due to a problem on my side. It would be great if I could toggle a TRACE of the HTTP exchange with an environment variable so I can see what is going on (e.g., MOJO_USERAGENT_DEBUG).

I can see there is the ability to trace the server parts of cro - I wonder if there is something for the client-side?

Thanks again for Cro.

**Comment by jnthn** [comment]
All `cro trace ...` does is set `CRO_TRACE=1` in the environment; it should work to do that with client pipelines too (in fact, I remember debugging the HTTP client that way).

Still to do is getting the trace output to be something nicer than just `.perl` of the message object, but still you can get the exact bytes being sent over the network.

**Comment by nige123** [comment]
Cheers - thanks Jonathan - that helps to see the objects behind the scenes. The client-side is up and running now. Going to start migrating the server-side Bailador app to Cro now :-)

**Comment by jnthn** [comment]
Some recent commits have also made the trace output nicer; [this tweet](https://twitter.com/croservices/status/905750973741760512) has a few images. Doing `CRO_TRACE=1` now gets the output in a more human-friendly form, rather than escaping all the newlines for the sake of `cro trace` which wants to parse and further format things. Also, the output is something nicer than `.perl` would give (hex dump for TCP messages, and the headers for HTTP messages).

**Comment by nige123** [comment]
Great - thanks. :+1:
